# Generated by Django 4.0.3 on 2022-03-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('private', models.BooleanField(default=False)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.user')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
