# Generated by Django 4.0.3 on 2022-03-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Categories',
        ),
        migrations.RenameField(
            model_name='doc',
            old_name='User',
            new_name='Categories',
        ),
        migrations.AlterField(
            model_name='doc',
            name='cover',
            field=models.FilePathField(),
        ),
    ]
